# Generated by Django 4.2 on 2025-11-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weight',
        ),
    ]
