# Generated by Django 4.2 on 2025-12-04 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_weightrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealrecord',
            name='meal_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
