# Generated by Django 5.2.7 on 2025-11-02 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietrecord',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='dietrecord',
            name='carbohydrate',
        ),
        migrations.RemoveField(
            model_name='dietrecord',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='dietrecord',
            name='food_name',
        ),
        migrations.RemoveField(
            model_name='dietrecord',
            name='meal_time',
        ),
        migrations.RemoveField(
            model_name='dietrecord',
            name='protein',
        ),
        migrations.AddField(
            model_name='dietrecord',
            name='date',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietrecord',
            name='food',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='food_records', to='core.foodnutrition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietrecord',
            name='meal_type',
            field=models.CharField(choices=[('아침', '아침'), ('점심', '점심'), ('저녁', '저녁'), ('간식', '간식')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietrecord',
            name='portion',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='dietrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_records', to='core.userinfo'),
        ),
    ]
