# Generated by Django 5.2.7 on 2025-11-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_dietrecord_calories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='height',
            new_name='height_cm',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='weight',
            new_name='target_weight_kg',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('low', '비활동적'), ('moderate', '보통'), ('high', '활동적')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='goal_type',
            field=models.CharField(blank=True, choices=[('loss', '감량'), ('maintain', '유지'), ('gain', '증량')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('M', '남성'), ('F', '여성'), ('O', '기타')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
