# Generated by Django 4.2 on 2025-11-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightrecord',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(
            name='weightrecord',
            table='records_weight',
        ),
    ]
