# Generated by Django 4.2 on 2025-11-22 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0002_alter_weightrecord_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.IntegerField(default=2)),
                ('goal_weight', models.FloatField(blank=True, null=True)),
                ('activity_level', models.IntegerField(default=3)),
                ('target_kcal', models.IntegerField(default=2000)),
                ('target_carb', models.IntegerField(default=250)),
                ('target_protein', models.IntegerField(default=120)),
                ('target_fat', models.IntegerField(default=60)),
                ('auto_mode', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
