# Generated by Django 4.2 on 2025-11-22 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_usergoal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergoal',
            old_name='target_carb',
            new_name='carbs',
        ),
        migrations.RenameField(
            model_name='usergoal',
            old_name='target_fat',
            new_name='fat',
        ),
        migrations.RenameField(
            model_name='usergoal',
            old_name='target_kcal',
            new_name='kcal',
        ),
        migrations.RenameField(
            model_name='usergoal',
            old_name='target_protein',
            new_name='protein',
        ),
        migrations.DeleteModel(
            name='NutritionGoal',
        ),
    ]
