# Generated by Django 4.2 on 2025-11-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_rename_target_carb_usergoal_carbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='sugar',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='target_carb',
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='target_fat',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='target_kcal',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='target_protein',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='target_sugar',
            field=models.IntegerField(default=50),
        ),
    ]
