# Generated by Django 4.2 on 2025-11-23 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_usergoal_sugar_usergoal_target_carb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergoal',
            name='target_carb',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='target_fat',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='target_kcal',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='target_protein',
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='target_sugar',
        ),
    ]
