# Generated by Django 4.2 on 2025-11-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_activity_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='activity_level',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='target_calories',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='target_carbs',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='target_fat',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='target_protein',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='activity_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='goal_calories',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='goal_carbs',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='goal_fat',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='goal_protein',
        ),
        migrations.AddField(
            model_name='usergoal',
            name='activity_level',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='goal_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='goal_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
