# Generated by Django 4.2 on 2025-11-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_activity_level_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGoal',
        ),
    ]
